Repository jeakfrw/jeak-framework, pull requests merged in 2019-06, with the labels that each got.

#16 Switch to single dependency strings for better tool integration
  build.gradle
Labels: bug, repository

#38 Fix null pointer when not setting any content-type
  src/main/java/de/fearnixx/jeak/service/controller/connection/HttpServer.java
Labels: bug

#43 Restructure REST authentication to be token focused and not controller focused
  src/main/java/de/fearnixx/jeak/service/controller/connection/ControllerRequestVerifier.java
  src/main/java/de/fearnixx/jeak/service/controller/connection/HttpServer.java
  src/main/java/de/fearnixx/jeak/service/controller/connection/IConnectionVerifier.java
  src/main/java/de/fearnixx/jeak/service/controller/testImpls/TestController.java
  src/main/java/de/fearnixx/jeak/service/token/ITokenService.java
  src/main/java/de/fearnixx/jeak/service/token/TokenConfiguration.java
  src/main/java/de/fearnixx/jeak/service/token/TokenScope.java
  src/main/java/de/fearnixx/jeak/service/token/TokenService.java
  src/main/resources/restService/token/defaultToken.json
Labels: breaking, enhancement, feedback wanted

#44 Remove deprecations ahead of next release candidate
  build.gradle
  src/api/java/de/fearnixx/jeak/IBot.java
  src/api/java/de/fearnixx/jeak/event/IQueryEvent.java
  src/api/java/de/fearnixx/jeak/reflect/JeakBotPlugin.java
  src/api/java/de/fearnixx/jeak/teamspeak/query/IQueryConnection.java
  src/api/java/de/fearnixx/jeak/teamspeak/query/IQueryPromise.java
  src/api/java/de/fearnixx/jeak/teamspeak/query/IQueryRequest.java
  src/api/java/de/fearnixx/jeak/teamspeak/query/QueryBuilder.java
  src/main/java/de/fearnixx/jeak/JeakBot.java
  src/main/java/de/fearnixx/jeak/event/query/QueryEvent.java
  src/main/java/de/fearnixx/jeak/plugin/persistent/PluginRegistry.java
  src/main/java/de/fearnixx/jeak/service/permission/teamspeak/AbstractTS3PermissionProvider.java
  src/main/java/de/fearnixx/jeak/service/permission/teamspeak/QueryPermissionProvider.java
  src/main/java/de/fearnixx/jeak/teamspeak/query/AbstractQueryConnection.java
  src/main/java/de/fearnixx/jeak/teamspeak/query/PromisedRequest.java
Labels: api, breaking

#50 Enable Buddy.Works CI
  .circleci/config.yml
  build.gradle
  distribution.gradle
Labels: repository

#51 Add null check for unannotated methods
  src/main/java/de/fearnixx/jeak/service/controller/controller/ControllerContainer.java
Labels: bug, enhancement, service
